name: Gradle Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gradle Tests
        run: docker run -it --rm -v ./:/app -w /app ghcr.io/ls1intum/eos:1.0.0 ./gradlew clean test
